### ISSUE TITLE
time of day, day of week

### ISSUE THREAD

**Issue by aghaynes** [CTU-Bern/kpitools#15]
**Is your feature request related to a problem? Please describe.**
Plots for time of day and day of week?

**Describe the solution you'd like**
@aghaynes has code

**Comment by mbranca** [comment]
This is for the recruitment? I also did something like this.

**Comment by aghaynes** [comment]
I have code for this...

![image](https://user-images.githubusercontent.com/6594028/122513292-8421f380-d00a-11eb-839a-3a296822a6a1.png)
